
@startmindmap


*:
Это мир, в котором живут всё когда либо
созданные людские образы и фантазии.
;

**:
Да, в этом мире есть города с более менее
развивающейся наукой и деревни,
но есть и относительно заброшенные территории,
на которых мало людей, и на этих территориях
живут мифические существа. В основном мир населен людьми,
но есть несколько особенных территорий
;

**:
Это мир как лоскутное одеяло, сшит нитями фантазий.
В местах разрыва живут призрачные души,
не оставившие след в жизни.
Также там есть территория, где живут боги,
закрытые защитными куполами и кричащие от своего безумия
;

*:
У главной героини по имени Эрика потерялся друг в горах.
Она была ещё слишком мала, чтобы отправиться на поиски,
но теперь она выросла, может за себя постоять и обеспечить
себя в путешествии, и хочет попробовать найти его.

Она думает, что он не просто пропал, а сбежал куда-то осознанно
;

**:
Они встретились в Старой Вехе - это название гостиницы для путешественников.
В ней люди ищут себе попутчиков в долгий путь.
Каждый из них пришёл туда найти попутчиков, им собрали команду,
в рамках которой они пообщались и решили отправиться в путь вместе
;



***:
Она встретит своего друга примерно на середине пути,
но не поймёт, что это он, так как он очень изменился внешне.
Однако в конце пути они снова встретятся и
она узнаёт его и останется с ним в мире фантазий.
;







*:
Вся история это путешествие компании.
Каждый задался какой-то своей целью, но они
помогают друг другу найти то, что им нужно.

Однако к концу пути, когда они нашли то, что искали,
большей части из них больше незачем оставаться
друг с другом и они разошлись.

А Эрика закрылась от своих, казалось,
новоприобретенных друзей, поняв, что это
было лишь временно, и прекратила с ними общение,
общается теперь только с её выдуманным другом Сашей и
одной из девушек, с которой она путешествовала
;

**:
В ходе путешествия персонажи раскрываются и меняются.
Эрика всегда тяжело общалась с новыми людьми,
Саша был её единственным другом (тот, который потерялся).
Она очень старается, и в целом у неё получается,
но в итоге люди в компании общаются между собой,
но не с ней, а она остаётся непринятым наблюдателем,
которого никто из них не понимает, как бы не старался
;

***:
Жалеет ли она о принятом решении? И да, и нет.
Это остаётся немного открытым.
Читатель поймёт, что это решение скорее всего было неправильным,
но почувствует безысходность ситуации и поймёт,
почему она отвернулась от своих бывших друзей
;

***:
Она поймёт к концу путешествия, что то, что её окружает,
лишь иллюзия и мир фантазий, но она откажется возвращаться
в реальный мир вместе с друзьями и останется здесь, в мире фантазий.

Может, после того как она расстанется с друзьями,
она отправится обратно в Земли Богов и
снова встретится там с Сашей, который уже обрёл память?
;

*:
Мы проходим через несколько ключевых локаций.
Мы пройдём через Ржавую Рощу, где будет скрываться древний волк,
из-за которого один из персонажей предаст нас и попытается убежать,
но случайно пересечёт границу призрачного утёса и навсегда останется призраком.
;

**:
Далее мы пройдём через Призрачный утёс,
где один из персонажей останется, достигнув своего желания,
а другой персонаж сможет пообщаться со своей семьёй.
;

***:
Далее вытоптанная Пустошь, где бродит ходячий замок под управлением Саши,
друга Эрики, который потерял свою память и потому замок ходит кругами
на одном и том же месте.
;

****:
Затем мы пройдём через земли богов, где один из персонажей
найдёт своё исцеление, а другой осознаёт свою любовь.
;

*****:
И затем мы прибудем в Глухую деревню рядом с землями богов,
где девушка, с которой мы продолжим своё общение, найдёт свою семью.
;



*:
Они действительно влюблены друг в друга. .

Эрика осталась в мире фантазий и может теперь идти куда хочет.
Куда она пойдёт? Я полагаю, что она пойдёт в Земли Богов.
Когда она была там с компанией, она встретила там бога,
который стал её приятелем. Скорее всего она пойдёт к нему
;

**:
В конце, когда она пройдёт весь путь, она поймёт,
что она не знает где искать его и уже почти отчается в поисках,
и потому перестанет его искать. Она не будет искать его специально,
но зато ОН - будет, так как вспомнит её
;

***:
Да, он вспомнит об её существовании и
сопоставит воспоминания с реальными событиями.
Он вспомнит её спустя пару недель, как встретится с ней.
;

****:
Когда она была в замке, она ему сказала,
что они отправятся в Земли Богов.
;

*:
Они не виделись три года.
К моменту встречи Эрика вымотана эмоционально и чувствует усталость,
а Саша, возможно, наоборот полон энергии и желания жить.
;

**:
Когда они встретятся, они точно будут рады видеть друг друга.
Пустота в душе Эрики заполнится.
Она снова обретёт своё потерянное счастье.

Здесь нужно сыграть на том, что это мир фантазий.
И выбирая Сашу, она выбирает свои фантазии, нежели реальность.
Поскольку Саша всегда был её воображаемым другом,
и она должна об этом узнать, когда принимает решение остаться.

Именно это решение должно побудить Сашу найти её,
как бы по её желанию, ведь это она его придумала.
;

***:
Я думаю нет. Слова Саши должны быть с горечью.
Ведь она выбрала его, а не реальность, а он всегда
хотел ей счастья и чтобы она могла выжить в реальном мире,
и потому ушёл от неё три года назад. Но она не справилась.
;

****:
Он должен говорить с сожалением о том, что Эрика
не смогла прижиться в реальности. А она будет отвечать,
что она будет счастлива с ним, а не с реальными людьми.
;

*:
Я думаю, в тот момент, когда она принимает решение остаться в этом мире,
должно что-то произойти. Что-то громкое.

Например, что-нибудь сломается. Её друзья прыгнут вниз,
в реальный мир, а она услышит громкий крик или какой-то звук
со стороны земель Богов. И увидит,
что вдалеке виднеется ходячий замок, который идёт в её сторону.
;

**:
Саша управляет замком и находится внутри.
Они должны встретиться через несколько часов после того,
как она его заметит. Она ещё будет размышлять над тем,
что совпадение слишком подозрительное
- она приняла решение остаться, и замок тут же появился. ;

***:
Она знает, что за рулём некий Чтец, старик,
но когда она принимает решение
- магия рассеивается и парень снова становится молодым.
;

*:
Итак, я уже написала их детство. Они были в лагере.
Я описала то, как они счастливы проводить там время вместе,
а затем переключила сцену на настоящее время,
где Эрика уже под другим именем (Каллисто) находится
в гостинице для путешественников.
Это сильный контраст, между домом, полного счастья, и пустой комнатой.
;

**:
Сцена детства уже написана, это не суть, им там около 15 лет.
Сейчас им примерно по 19-20.

Итак, Эрика  в гостинице. Она просыпается в холодной кровати, встаёт,
её приглашают познакомиться с другими членами команды.
;

***:
Ей снилось её детство,, но она проснулась и чувствует себя несчастной.

Она проходит в комнату, где живут её будущие товарищи,
знакомится с двумя, а затем они спускаются вместе в столовую.
Там они общаются с их куратором, который подводит их к ещё двум девушкам.
Эти девушки готовили еду для похода, и
мы знакомимся с ними, пока они выбирают мясо из закромов
;
@endmindmap