@startuml
component 1 [
-<b> буркнул Вар, пристально вглядываясь в темноту перед собой.

•<b>	Что ты несешь, Вар? - возмутился Владик, прищурившись
от непонятного разговора. - Мы все знаем, что шубы у тебя давно нет,
так что не надо здесь делать вид, будто это вдруг проблема.

•	<b>Ну, тут несколько проблем, - возразила Вики, поддерживая Вара.
- Проблема в том, что ты слишком много думаешь о своем комфорте,
Влад, а не о том, как выбраться отсюда.

•	<b>Это не так, - сказал Владик, поправляя свой рубаху.
- Я лишь говорю, что этот крот, возможно, совершил мудрый выбор,
а мы, сидя здесь и обсуждая, кто прав, а кто нет, просто теряем время.

•	Неужели вы все думаете, что мы просто так пойдем за этим зверем?
- возмутился Вар, поднимая руки в знак бессилия.
<b>- Неужели никто не видит, что это все игра, что нас тут держат за идиотов,
 <b>кормя разными тупыми загадками и непонятными намеками?
 <b>Вам не кажется, что нам пора уже проснуться от этого кошмара?

•	<b>Это ты просто слишком много думаешь о своих проблемах,
<b>- бросила Вики, презрительно качая головой.
<b>- Что касается меня, я предпочитаю верить, что в нашем путешествии
<b>есть смысл, и что мы найдем выход, даже если для этого придется
последовать за кротом.

]

component 2 [
•	Друзья мои, неужели вы думаете, что мы пропустили
какой-то незаметный коридорчик, скрытый за кучей корней?
- с иронией спросил Вар, с укоризной глядя на своих спутников.
- Кажется, это просто бред сивой кобылы.

•	Ну, Вар, не стоит так уж и жестко... - начал Владик,
прервавшись, когда увидел выражение лица Вики, которая уже
была готова включиться в спор.

•	Да не переживай, Влад. Вики сейчас всему научит!
- саркастически пошутил Вар, слегка хмыкнув.
Но когда он заметил недовольный взгляд Вики, он быстро добавил:
- Ладно, извини, просто юмор такой. Но я действительно не
вижу смысла в этом бесконечном замечании о возможных ловушках.

•	Это не ловушки, Вар, а реальные опасности!
- возразила Вики, чувствуя, как накаляется обстановка.
- Мы не знаем, что нас ожидает за следующим поворотом.

•	Ну что ж, если вы все так переживаете, давайте поиграем
в «где крот пропал»! - Владик внезапно решил привнести легкость
в обстановку. - Вар, вот посмотри, что я нашел.
Наверняка это следы нашего дорогого друга-крота.

•	Ну конечно, как я мог не заметить этот потрясающий артефакт,
- ответил Вар, сдаваясь под напором энтузиазма Владика.
- Но если ты так хочешь, что тут скажешь?

•	Вот и отлично! - воскликнул Владик, радуясь, что
наконец-то получил поддержку. - Теперь, кто готов угадать,
в какую сторону пошел наш кротище?

•	Ладно, давай, Вики, покажи нам свои таланты интеллектуала,
- призвал Вар, снова добавляя порцию сарказма в общую атмосферу.
Вики, с тонким улыбкой, развязала платок и начала объяснять
свою логику. Каждое ее слово было пропитано размышлениями и
заумными оборотами. После тщательных рассуждений и демонстрации,
она пришла к выводу о том, в какую сторону двигался крот.
Владик, удовлетворенно улыбаясь, одобрил ее выводы, а Вар
поддержал решение продолжить путь в указанном направлении,
добавив при этом немного своего особого юмора.

]
component 3 [
•	Владик, можешь не волноваться, что мы пропустим какой-то коридорчик?
- спросил Вар, его голос звучал устало и разочарованно.
- Почему бы и нет? Неважно, что упустили, в конце концов,
это ведь не повлияет на то, найдем ли мы Каллисто.

•	Что, ты думаешь, нам всё равно, где наша подруга?
– Владик, руководящий экспедицией, в своих словах прозвучало
молодецкий просторечный дух. - Нет, конечно. Но поиск каждой
мелочи не поможет нам найти ее быстрее, здесь уже слишком многое
упущено. Вики, тебе это не нравится?

•	Вам какие-то панические атаки, что ли, накатывают?
- задумчиво промолвила Вики, мечтательно глядя вдаль.
Ее слова были спокойными, словно она уже заранее знала
ответы на все вопросы. - Но вы почему-то не рассматриваете
самый очевидный вариант. Может, это именно то, что нам нужно?

•	Ты про что, а? - переспросил Вар, криво ухмыляясь.
- На всякий случай можешь обьяснить?

•	Отлично, развлекайтесь. - Владик улыбнулся, глядя на Вики,
словно она была какой-то магом в его собственной драме.
- Мы ждем твоего космического разгадывания.

•	Если ты присмотрись, - начала она, но не договорила, подходя к стене.
- Давай сделаем вид, что ты - стена, а я - лабиринт. Всё стало ясно?

•	Что? - удивленно произнес Вар, отводя взгляд от Вики.
- Что значит "все стало ясно"?

•	Ах да, забыла, что в мире мужчин смысловой контекст может
быть не очевидным. - Вики сделала паузу, словно наставляя Вара.
- Ладно, представь, что моя рука - это ветка, а ты - суперкрот.
Проходи отсюда, иди налево. Вики отвела Вара к стене,
указывая на корень, зацепивший мех. Затем она вдруг как будто забыла,
что они не в старом городском парке, и стала вальяжно ходить,
словно огромный крот.

•	Ну, что там у тебя с мехом? - сказала она, юмористически
подражая кроту. - Вики, стоящая вправо, говорит: "Ты, смотрю,
любишь идти налево".

•	Я думаю, нам лучше идти направо. - Вар тоскливо улыбнулся,
как будто только что пошутил.

•	Вот и отлично. Можем идти. - Владик, развлекаясь подробностями
плана Вики, вдруг решил дать ей почувствовать свою поддержку.

]
component 4 [
Владик:
"Видишь ли, Вар, бояться нам некогда. У нас ещё туча дел перед глазами,
как наши предки говорили. Но, конечно, развилка нам не помешает,
тут ты прав. Может, какой-то крошечный проходчик за этой стеной прячется,
чего там скажешь," проговорил Владик, кивая в сторону пересохших корней.
"Но думаю, это не помешает нам отыскать нашу драгоценную подругу,
да и сам не повредит."

Вар:
"Так, ты думаешь, Владик, что наши ратные усилия действительно
окажут влияние на эту бесконечную путаницу?" поинтересовался Вар
с издевкой в голосе. "Вот нас тут, невидимо для света божьего,
сквозь этот чертов лабиринт тянет, а кроме пыли и корней ничего
найти не можем. Может, кто-то вообще сверху не допускает нас
к нашей дороге, а мы тут, как глупые ослы, тратим силы и нервы."

Вики:
"А вы, господа, думаете, что мы тут в этом архаичном замкадье
заблудились случайно?" заговорила Вики, смотря на своих спутников
с призрачной улыбкой. "Может, это часть какого-то древнего обряда,
удерживающего нас в этой чертовой ловушке? Или может, мы просто
подготавливаем землю для очередной жертвы в пользу старых богов?"
Вики таинственно посмотрела на Владика, словно ожидая, что тот
подтвердит её догадки.

Владик:
"Слава богам, что я не настолько начитанный, чтобы поддаваться
этому бреду," философски ответил Владик, кивая на Вики.
"Да что там думать, девчонка? Мы здесь потому, что кто-то заблудился.
А если вдруг кто-то действительно пошлет нам сюда в подарок,
так на них, их всех, мы найдем наш путь, даже если нам придется
выкапывать его вручную."

]
component 5 [
- Владик, ты не боишься, что мы могли пропустить какую-нибудь развилку?
– спросил Вар. – Какой-нибудь маленький, незаметный коридорчик,
скрытый за кучей корней…

- Да вполне могли… - тихо ответил Влад. Заметив появившееся
беспокойство на лице Вара, он тут же поправился:
- Конечно, это не повлияет на то, заблудимся мы или нет.
А вот на то, найдем мы нашу дорогую подругу или нет
– очень даже может повлиять.

- А что, если мы идём, а за нами корни замыкаются?
Как мы дорогу назад найдём? – затараторила Вики и начала
нервно оглядываться. – А если потолок обвалится? А если…

- Так, а ну-ка отставить панику! – чуть повысил голос Владик.
– Везде солому не постелешь. Если хочешь, можешь начать придумывать
тысячу и один способ сбежать из лабиринта.

- Например, когда отрезан доступ к кислороду, во всех близлежащих
коридорах осыпался потолок, а ты вообще заперта в одном пространстве
с огромным кротом. – подхватил Вар.

Владик ухмыльнулся, наблюдая, как мозг Вики лихорадочно заработал,
но не дал мыслям завладеть ею полностью и добавил:

- Можешь потом об этом подумать. А пока что глянь вот сюды. Давай, смелее.
Владик показал куда-то перед собой. Вики подошла поближе и попыталась
рассмотреть его находку. На земле лежал клочок меха. Скорее всего,
когда крот пробирался по туннелю, он зацепился за очередной корешок,
торчащий из стены. Вики подняла взгляд. Действительно, сверху торчала
особо неприятная на вид ветка, на которой тоже осталось немного шерсти.

- Если смотреть на то, как именно зацепился мех, крот пошел налево,
- тут же начала рассуждать Вики.  Владик улыбнулся. Он чувствовал
себя так, как будто только что подарил ребёнку весьма интересную игрушку.

- Почему ты так решила? – поинтересовался Вар.

В ответ Вики решила не ограничиваться рассуждениями и развязала
платок, закрепленный на плече.

- Смотрите. Давай представим, что твоя рука — это ветка. Встань вот сюда. Я буду кротом.
Вики подвела парня к стене, из которой торчал корень, и подняла его руку,
показав, как надо держать. Затем, сделав несколько шагов в сторону,
она смешно надула щеки и вальяжно прошагала вдоль земляной стены
справа налево. Подойдя к Вару, она как бы ненароком задела его руку
платком и прошла чуть дальше, а когда ткань натянулась, остановилась.

- Ой-ой-ой, как же так, я, такой большой и важный крот,
зацепился за что-то своим мехом! Теперь этот мех застынет вот в
таком положении, потому что это мягонький легкий подшерсток, который
не выпрямится и не упадет. Ну, по большей части. И такое положение меха
говорит о том, что я шел налево.

Вики закончила объяснение. Раздались бурные аплодисменты в исполнении
Владика. Вики поклонилась и вернула платок на плечо. Вар вздохнул.

- Я, конечно, нифига не видел, но я всё понял. Пошли направо.

Владик расхохотался. Вики буркнула себе под нос что-то про куриц ночью,
 и хотела уже начать спорить, однако Владик оказался первее.

- Как ни странно, Вар прав. Это могло быть неделю назад, две недели,
три, он мог пройти и вернуться обратно, он мог выбираться изнутри или
наоборот идти наружу, просто к другому выходу. Мы не можем менять маршрут
просто так. Где сейчас это животное – одному богу известно.

Вар снова как-то двусмысленно хмыкнул. Вики закатила глаза.

- Ну а сейчас-то что не так? – спросила она.

- Он так сказал, как будто знает, какому именно богу это известно. – отозвался Вар.

]
component 6 [

]
component 7 [

]

component 8 [

]



@enduml