@startuml
start

partition #pink/white "Знакомство с основными персонажами, Старая Веха" {

#defbff:<b>Глава "Тепло прошлого"
Флэшбек.

Знакомство с Эрикой и Сашей, теплая атмосфера
дружбы и поездки в детский лагерь,
первое упоминание слова "Каллисто".

В дальнейшем персонаж фигурирует
именно под этим именем;

:<b> Глава "Принятие" (черновое название)
Перемещаемся в текущее время.
Первый день в гостинице. (для читателя)

Гостиница "Старая Веха" - скудная комната
на контрасте с тем, что было в том лагере.

Чувство одиночества, сбивающееся
необходимостью познакомиться с другими
путешественниками из команды
(с пинка Владика - куратора её отряда)

Из контекста становится понятно, что
Каллисто на днях заселилась в гостиницу,
чтобы найти попутчиков для поиска Саши,
пропавшего где-то и когда-то,
не указывается, когда и почему

Странное и чуждое чувство принятия
Варом и Спиритом, с которыми она поговорила;

:<b>Глава "Третья"
Совместный завтрак (4 перс), болтовня, пояснение
Владиком дальнейших планов на ближайшие дни,
он говорит, что набрал полный отряд, и если
всех всё устроит, то отправляются
через несколько дней;

if (<b>Глава "Четвертая"\nЗнакомство с Аюной и Вики) is (Много активного, живого взаимодействия\nСплочение команды, знакомство через действия\nЗнакомство через <b>позитив) then
    :Когда они вышли на уличную кухню,
    чтобы распределить обязанности по
    подготовке к походу;

    :Подготовка к походу (заготовка припасов);

    :Закупка некоторых ингредиентов
    у приезжих торговцев, плюс возможно сбор
    части урожая или покупают из запасов гостиницы;
else (Только уровень "услышать и увидеть чуваков",\nОстается осадок для размышлений и рефлексии\nЗнакомство через <b>негатив)
    :Перед медосмотром - обычная процедура
    в процессе подготовки к походу;
endif

:<b>Глава "Пятая"
Второй день в гостинице
Тренировка с оружием на поляне в лесу

Укрепляет боевые навыки группы,
раскрывает основные опасности в этом мире
и способы борьбы с ними

Подробнее объясняется, зачем существует "Старая Веха"
(проводники, работающие здесь, опытные путешественники);

:В конце главы неожиданно со стороны леса
слышен шум, небо темнеет, а из-за деревьев
выбегает стая волков;

}

partition #c0fad4/white "Арка Диззи и Инверто, Ржавая Роща" {

:<b>Глава "Шестая"
Все, кто тренировался на улице, наставляют оружие
в сторону волков, но те мчатся мимо них как будто в испуге

Среди волков появляется особо выделяющаяся по внешности
волчица, вдруг прокричавшая, что не нужно атаковать волков,
они бегут не на людей, а от опасности внутри леса

Она убеждает людей не атаковать их
(пара случайных выстрелов в их сторону для пущего пафоса?)

Знакомство с Диззи
Она кратко объясняет что произошло
Владик говорит, что им скоро отправляться в ту сторону;

:Диззи предлагает сделку. Какую?
Она станет их проводником и союзником, если...;

split
   :Если они помогут её убить Инверто.
   Его поразило проклятие и он не может
   больше выполнять обязанности хранителя леса;

   if (А что потом?) then
    :Ну он просто сдохнет и
    кто-то займет мб его место
    Может быть даже она сама;
   else
    :Он переродится и снова будет
    норм чуваком и все такое;
   endif

split again
   :Если они помогут ей излечить Инверто
   Но непонятен способ излечения.;
split again
   :Просто так.
   Потому что она важный волк из леса.
   Потому что хранители леса и все такое.
   Сомнительно. Зачем ей это?;
end split
:Компания сомневается, но соглашается на сделку (предложение);

:Они договариваются о встрече и обсуждении плана действий
Просят Диззи прийти на сегодняшний ужин у костра
Она соглашается;

:<b>Глава "Седьмая"
Путешественники собираются у костра
Обстановка в целом довольно расслабленная,
несмотря на кипиш в лесу сегодня

Слышны песни, частушки, рассказы
Люди жарят мяско, картошку, зефирки, грибочки
Кто-то готовит супчик;

split
:Диззи приходит в обличье волка;

split again
:Диззи приходит в обличье человека;
:Это становится доп темой для разговора
и пояснения, что происходит с лесом;

end split

:Диззи подробнее поясняет за кипиш в лесу
Путники впервые публично заявляют о своих целях
в этом походе
Убедились в том, что им плюс минус по пути
Приятное завершение вечера,
назначена точная дата и время отправления;

if (Предложим Диззи остаться на ночь?) then

split
:Владик предложил
Диззи остаться;
split again
:Каллисто попросила
Диззи остаться;
split again
:Диззи сама
попросилась остаться;
end split

if (Согласилась?) then (да (а как с деньгами кстати?))
    :Осталась в комнате Каллисто
    Душевные разговоры на ночь
    Развеивается чувство одиночества;

    if (Приходила в обличье волка?) then (да)
        :Превращается во сне в человека;
        if (Каллисто замечает это?) then (да)
            :Подозревает Диззи в обмане, но
            решает ничего никому не говорить,
            мало ли какие причины есть;
        else (нет)
            :Это известно только читателю;
        end if


    endif
else (нет)
    :Ушла в лес;
endif

else
:Никто ничего не предлагал
Диззи ушла обратно в лес
до назначенного времени отправления;
endif

#defbff:<b>Глава "Восьмая"
Сон Каллисто

Сцена с Сашей, разговоры с ним на улице,
короче ее плющит, она скучает,
можно сказать, что разговаривает со своей совестью

Саша ей советует подружиться с этими ребятами
Во сне идет дождь, а на утро на улице трава мокрая;

:<b>Глава "Девятая"
За кадром проходит несколько дней
Отряд отправляется в Ржавую Рощу

Первый день в Ржавой Роще
Рассказывается история этого леса
Описывается, что они видят вокруг себя

Ламповая ночевка в одном из старых домов внутри леса;

#defbff:Сон Каллисто (опционально, но как будто бы важно?)
Целая глава или кусок девятой главы?

Сцена с Сашей, в которой он
предупреждает ее об опасности
и спрашивает, почему она доверилась Диззи

Можно даже поругаться тут с ним немного,
но в итоге помириться;

:<b>Главая "Десятая"
Второй день в Ржавой Роще
Топ-топ-топ, ой, а что-то вокруг всё потемнело,
а что-то как-то страшно и некомфортно вообще вокруг;

:Встреча с Инверто.
Выясняется, что Инверто просто хотел поглумиться и
сожрать их всех. Диззи скрывается из виду.
Происходит особо острый конфликт Инверто с Варом

На фоне того, что Инверто видит в Варе знакомые
тёмные черты, от которых тот хочет излечиться,
Инверто принимает решение усугубить ситуацию и заражает
его частью своей скверны. Вар теряется сознание.;

:Aюна использует магию огня
(никто не знал, что она так может),
уничтожает Инверто. Это вызывает страх у остальных,
но она спасла их;

:<b>Глава "Одиннадцатая"

Когда Диззи скрылась из виду, она присоединилась к стае.

Когда стая увидела, что Аюна расправилась с Инверто,
она обернулась против Диззи и приняла решение убить её,
предательницу, приведшую в лес таких опасных людей.

Диззи пытается убежать, преследуемая волками

Диззи случайно заступает за границу Призрачного Утёса
и становится призраком (весьма печальная картина);
}

partition #e0e1ff/white "Арка Спирита, Призрачный утес" {

:<b>Глава "Двенадцатая";
split
:Инверто мертв;
split again
:Инверто переродился
и как будто бы Диззи не на 100% им наврала;
end split

:Как в обоих случаях ведет себя стая?
Видят ли герои это,
Видит ли это читатель,
или это остается за кадром?;

split
:Путники оклемались и вернулись в дом,
в котором ночевали ранее, передохнули
и отправились дальше на Призрачный утес;

note right
Ненужное
возвращение?
end note
split again
:Путники оклемались, вышли из леса
в сторону Призрачного утеса, обсудили,
что за треш произошел, и разбили лагерь перед
утесом, чтобы на следующий день отправиться к нему;
end split

:Владик рассказывает, что есть особые места на
Призрачном утесе, через которые можно относительно
безопасно проходить. Путь становится еще безопаснее,
если человека проводит дух или полудух, поэтому,
когда люди отправляются через утес, обычно ищут
подходящего духа/полудуха, и Спирит один из них;

:Ночевка;

:<b>Глава "Тринадцатая"
Выступаем на утес... все я усталь писать уже два часа ночи;


}




stop
@enduml
