@startuml
'https://plantuml.com/activity-diagram-beta

start

:Мы оказываемся на Призрачном утесе;

:Какое-то время идем, описывается то, что мы видим, кого видим;

group #ivory Призрачный утес - Владик очнулся и помогает Вики и Вару

#orange:Я пока не придумала как, но, вероятно, от того, что
им пришлось заночевать на нем, их мысли увели их куда-то далеко
и потому утром они уже были в совсем разных местах;

:Холодно. Сыро. Все-таки, есть минусы в том, чтобы спать в горах или
в скалистой местности. Владик проснулся от того, что его спальный мешок промок.
Похоже, из-за ветра ночью стенки внешней палатки немного сместило, из-за чего
весь конденсат перетек во внутреннюю палатку и остался лужицей у входа палатки;

:Владика пытались охватить воспоминания. Они шептали ему
что-то, но он очень легко от них отделался, и говорит,
что он не жалеет ни о чем, что он сделал в прошлом;

:Он находит Вики, которая мысленно снова была
вместе со своей наставницей. Вернуть ее к реальности
получается призывами к поиску истины, к путешествиям,
ведь она умная девушка и она знает, <i>что</i> на самом деле
случилось с ее наставницей;

:Вики вместе с Владиком каким-то чудом помогает Вару
Что он видел в воспоминаниях - я пока не знаю, но можно
связать это с предательством Диззи, ее духом, который живет
теперь на Призрачном утесе и тем, как именно этот дух
окажет влияние на Вара;

end group


group #lightcyan Призрачный утес - воспоминания Каллисто

:Эрика подошла к кирпичному пятиэтажному дому. Это был не первый раз,
когда ее попросили объяснить что-то по математике. С тех пор,
как она начала подрабатывать преподаванием, прошло не так много времени,
но она уже успела поднабраться опыта.

Сегодня ее попросили провести занятиее с мальчишкой-девятиклассником.
Такая просьба немного удивила Эрику. До этого ее просили
заниматься с детьми 5-7 класса, и в основном знакомые.
Сама она только закончила 10 класс, и сейчас ее немного смущало то,
что ей предстоит объяснять что-то ребенку, который был всего на год младше
ее самой.

Она улыбнулась. Она и сама, по сути, еще ребенок.;


:Сцена знакомства, где они впервые сели заниматься
математикой и немного астрономией;

:Затем Каллисто видит счастливые воспоминания.
Она(еще Эрика), Саша, его родители, чувство семьи,
но оно должно ощущаться с небольшой грустинкой.

Саша должен в конце проводить ее,
чтобы она пошла домой, со словами типа:

"Прости... я не могу позволить тебе остаться.
Тебе нужно домой. Ты ведь не думаешь, что так...
будет продолжаться вечно?";

split
#orange:Когда Саша пропал, его родители приехали в лагерь,
устроили скандал с управляющими лагерем,
плачут от того, что их сын потерялся, когда говорят с Эрикой.
Она тоже чувствует слезы на глазах,
злится, и обещает, что вернет его, и уходит от них

и в итоге еще месяц они
пробыли там, даже тогда, когда Эрика уже уехала;


#orange:Рубрика "Интересные факты"
Саша - выдумка, его родители - тоже выдумка
На самом деле никакие родители не приезжали и
это она сама устроила скандал, на основании чего
её отправили в больницу, вкололи успокоительное
и все такое. Она этого не помнит, но до конца лагеря
она пробыла в больнице, и даже после того, как
она приехала домой, за ней наблюдали в больнице
и она принимала лекарства.

Это одна из причин ее заторможенной реакции
на потерю Саши и того, что она не очень хорошо
помнит, что было сразу после его потери;
split again

:Ничего больше не описывается,
сразу переход на сцену, когда
родители плачут (у них дома);

:Каллисто видит его родителей, плачущих от того,
что их сын потерялся. Она тоже чувствует слезы на глазах,
злится, и обещает, что вернет его, и уходит от них;
end split



:В этот момент она очнется от "глюка",
который словила на Призрачном утесе;

end group

group #application Каллисто помогает Аюне

:Каллисто находит Аюну, которая снова видит тот пожар,
в котором, как она думает, сгорел не только ее дом,
но и ее родители по ее вине.

Как мы ее вытащим, я пока не знаю.;

:Но мы ее вытаскиваем, и затем встречаемся с остальными,
ищем Спирита, думаем, что он тоже глюк словил, но нет,
он ничего не ловил, ему вообще очень хорошо и классно,
он там летает, веселится с призраками, мы чувствуем себя странно,
ведь технически он нас бросил в бреду и пошел развлекаться;

:Где-то здесь мы должны увидеть призрака, который
расскажет нам о том, что от него почти ничего не осталось,
и мы понимаем, что от Спирита тоже ничего не останется;


:В итоге он остается на призрачном утесе, потому что
сам так захотел;


end group


:Призраки с утёса сказали нам, что нам нужен Чтец,
когда Каллисто сказала, что она ищет пропавшего друга и т.д.;


:Они скажут про вытоптанную пустошь
(выветренную пустошь) (изрытую пустошь);


:Мы покидаем Призрачный утес в спешке, не засыпая до глубокой ночи,
а когда вышли с утеса, тут же завалились спать;

:Когда путешественники подходят к Вытоптанной пустоши, они видят
смерчи пыли и грязи, но среди ветра они вдруг замечают горячие глаза
и большое тело. Похоже, какое-то животное заметило их. Они
испугались, но оно не стало нападать, а забралось куда-то под землю;

:Подземный лабиринт. Как они и думали, идти по нему оказалось
тем еще мучением. Из стен торчали корни деревьев, земляной потолок
местами обвалился и потому по некоторым туннелям проходить было
намного сложнее.

(превратить текст, где путешественники пробираются сами);

:Жестокие порывы ветра остались наверху, вместе с остатками
солнечного света.
Ветер угрожающе завывал и безуспешно пытался добраться
до путешественников. Он остался позади - там, где дышать
и видеть хоть что-то без куска ткани на лице было невозможно;


:Каллисто обернулась в сторону неровного, вырытого огромным
животным прохода. Свет едва проходил сквозь пылевой смерч,
бушевавший снаружи. Теперь, когда страшные порывы ветра не пытались
сбить ее с ног, а пыль не пыталась наполнить собой ее легкие,
Каллисто стянула ткань с лица. Они уже отошли достаточно далеко
от входа, чтобы (зажечь фонари и их не сдуло);

:идут идут идут;

:В конце земляного туннеля лежал человек.;

split

:Вокруг него ничего нет,
что говорило бы о том,
что он здесь живет.
Похоже, он просто существует здесь;

split again

:Там была подстилка из травы, игравшая
роль кровати, запасы кореньев и воды.
Дырка в потолке для выхода воздуха.;

split again

:Здесь был дом. Похоже, это был один
из тех домов, что провалились под землю
от того, что рылись все эти бесконечные туннели.;

end split;

:Окей, питается он в основном корнями, но иногда крот
(который на самом деле его собака) приносит ему мясо
(ловит какое-нибудь животное, типо птицы);

:Можно, кстати, заставить его поймать Каллисто и утащить вниз;

:Можно, чтобы это животное она встретила в самом начале вместо того медведя;


:- Тот, кто придумал этот мир, жесток, как ребенок, но для ребенка
все же слишком... последователен.

У Каллисто похолодели руки.

- Думаю, он испытывает какое-то странное удовольствие от моих страданий.
Как думаешь, может мне в пору считать его психопатом? - Чтец потянулся
рукой к кроту и погладил его. - Может, даже моя смерть была бы
не такой жестокой.;

:Подтект: Каллисто, создавшая этот мир, Сашу, отправилась
в путешествие, воссоздав эти образы, преобразовав их, обрекла их на страдания;

:- Разве ты не сам виноват в своей судьбе? - перебила его Каллисто.
В ней кипели смешанны чувства. С одной стороны, ей было безумно
жаль этого человека, а с другой она очень сильно злилась.
Как можно было довести себя до такого состояния? Как можно так
наплевательски относиться к себе, к своему телу? Как можно накрутить
себя, зациклиться на чем-то так сильно, что не замечаешь ничего вокруг?;

stop

@enduml
