@startuml
'https://plantuml.com/activity-diagram-beta

start

:Мы оказываемся на Призрачном утесе;

:Какое-то время идем, описывается то, что мы видим, кого видим;

group #ivory Призрачный утес - Владик очнулся и помогает Вики и Вару

#orange:Я пока не придумала как, но, вероятно, от того, что
им пришлось заночевать на нем, их мысли увели их куда-то далеко
и потому утром они уже были в совсем разных местах;

:Холодно. Сыро. Все-таки, есть минусы в том, чтобы спать в горах или
в скалистой местности. Владик проснулся от того, что его спальный мешок промок.
Похоже, из-за ветра ночью стенки внешней палатки немного сместило, из-за чего
весь конденсат перетек во внутреннюю палатку и остался лужицей у входа палатки;

:Владика пытались охватить воспоминания. Они шептали ему
что-то, но он очень легко от них отделался, и говорит,
что он не жалеет ни о чем, что он сделал в прошлом;

:Он находит Вики, которая мысленно снова была
вместе со своей наставницей. Вернуть ее к реальности
получается призывами к поиску истины, к путешествиям,
ведь она умная девушка и она знает, <i>что</i> на самом деле
случилось с ее наставницей;

:Вики вместе с Владиком каким-то чудом помогает Вару
Что он видел в воспоминаниях - я пока не знаю, но можно
связать это с предательством Диззи, ее духом, который живет
теперь на Призрачном утесе и тем, как именно этот дух
окажет влияние на Вара;

end group


group #lightcyan Призрачный утес - воспоминания Каллисто

:Сцена знакомства, где они впервые сели заниматься
математикой и немного астрономией;

:Затем Каллисто видит счастливые воспоминания.
Она(еще Эрика), Саша, его родители, чувство семьи,
но оно должно ощущаться с небольшой грустинкой.

Саша должен в конце проводить ее,
чтобы она пошла домой, со словами типа:

"Прости... я не могу позволить тебе остаться.
Тебе нужно домой. Ты ведь не думаешь, что так...
будет продолжаться вечно?";

split
#orange:Когда Саша пропал, его родители приехали в лагерь,
устроили скандал с управляющими лагерем,
плачут от того, что их сын потерялся, когда говорят с Эрикой.
Она тоже чувствует слезы на глазах,
злится, и обещает, что вернет его, и уходит от них

и в итоге еще месяц они
пробыли там, даже тогда, когда Эрика уже уехала;


#orange:Рубрика "Интересные факты"
Саша - выдумка, его родители - тоже выдумка
На самом деле никакие родители не приезжали и
это она сама устроила скандал, на основании чего
её отправили в больницу, вкололи успокоительное
и все такое. Она этого не помнит, но до конца лагеря
она пробыла в больнице, и даже после того, как
она приехала домой, за ней наблюдали в больнице
и она принимала лекарства.

Это одна из причин ее заторможенной реакции
на потерю Саши и того, что она не очень хорошо
помнит, что было сразу после его потери;
split again

:Ничего больше не описывается,
сразу переход на сцену, когда
родители плачут (у них дома);

:Каллисто видит его родителей, плачущих от того,
что их сын потерялся. Она тоже чувствует слезы на глазах,
злится, и обещает, что вернет его, и уходит от них;
end split



:В этот момент она очнется от "глюка",
который словила на Призрачном утесе;

end group

group #application Каллисто помогает Аюне

:Каллисто находит Аюну, которая снова видит тот пожар,
в котором, как она думает, сгорел не только ее дом,
но и ее родители по ее вине.

Как мы ее вытащим, я пока не знаю.;

:Но мы ее вытаскиваем, и затем встречаемся с остальными,
ищем Спирита, думаем, что он тоже глюк словил, но нет,
он ничего не ловил, ему вообще очень хорошо и классно,
он там летает, веселится с призраками, мы чувствуем себя странно,
ведь технически он нас бросил в бреду и пошел развлекаться;

:Где-то здесь мы должны увидеть призрака, который
расскажет нам о том, что от него почти ничего не осталось,
и мы понимаем, что от Спирита тоже ничего не останется;


:В итоге он остается на призрачном утесе, потому что
сам так захотел;


end group

:Мы покидаем Призрачный утес в спешке, не засыпая до глубокой ночи,
а когда вышли с утеса, тут же завалились спать;

stop

@enduml
